name: E2E Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  chrome:

    runs-on: ubuntu-latest

    steps:
    - name: Get Code
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Setup Python
      uses: actions/setup-python@v5.6.0
      with: 
        python-version: 3.12
    - name: Install Deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Browser init
      run: rfbrowser init
      
    - name: Run E2E tests
      run: robot -d ./logs -v BROWSER:chromium tests

    - name: Robot Reporter
      uses: joonvena/robotframework-reporter-action@v2.4
      with:
        gh_access_token: ${{ secrets.GITHUB_TOKEN }}
        report_path: logs

    - name: Upload Report
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Test Report
        path: logs

  firefox:

    runs-on: ubuntu-latest

    steps:
    - name: Get Code
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Setup Python
      uses: actions/setup-python@v5.6.0
      with: 
        python-version: 3.12
    - name: Install Deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Browser init
      run: rfbrowser init
      
    - name: Run E2E tests
      run: robot -d ./logs -v BROWSER:firefox tests

    - name: Robot Reporter
      uses: joonvena/robotframework-reporter-action@v2.4
      with:
        gh_access_token: ${{ secrets.GITHUB_TOKEN }}
        report_path: logs

    - name: Upload Report
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Test Report
        path: logs